# Essential setup for GitHub deployment
backend:
    name: git-gateway
    branch: master

# Don't style muh backend
skip_render:
  - "*admin/*"

# Media handling
media_folder: "source/assets"
public_folder: "/assets"

# Collections
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
        - {label: "Layout", name: "layout", widget: "hidden", default: "blog-single"}
        - {label: "Categories", name: "categories", widget: "hidden", default: "blog"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime" }
        - {label: "Keywords", name: "keywords", widget: "string"}
        - {label: "Excerpt", name: "description", widget: "string"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "_posts/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
        - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio-single"}
        - {label: "Categories", name: "categories", widget: "hidden", default: "portfolio"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime" }
        - {label: "Description", name: "description", widget: "string"}
        - {label: "My Role", name: "myRole", widget: "string"}
